### PR TITLE
Simple code

### PR DESCRIPTION
**Pull request by xuri**

### CODE REVIEW

**Comment by sandyskies** [comment]
@xuri  should go to dev branch ，see https://github.com/TarsCloud/TarsGo/blob/master/CONTRIBUTING.md

**Comment by sandyskies** [comment]
@xuri  should go to dev branch ，see https://github.com/TarsCloud/TarsGo/blob/master/CONTRIBUTING.md

**Comment by sandyskies** [comment]
should change base branch to dev

**Comment by xuri** [comment]
@sandyskies base branch has been changed to `dev`.

**Comment by xuri** [comment]
@sandyskies base branch has been changed to `dev`.

**Comment by xuri** [comment]
@sandyskies base branch has been changed to `dev`.

**Comment by sandyskies** [comment]
close this pr ，because of the wrong base branch，Thanks for  contributing，please make other pr again

**Pull request closed without merging**
