### PR TITLE
tars: fix various problems

### PR DESCRIPTION
**Pull request by chenhengqi**
This PR fixes the following problems:

1. run `go fmt` against the code base
2. fix several problems identified by `go vet`, such as unreachable code, broken tests, missing struct field names.
3. bump openzipkin-contrib/zipkin-go-opentracing to v0.4.5, fix broken plugin
4. fix typo, `zombile` to `zombie`

### CODE REVIEW

**Comment by defool** [comment]
Good job, have any new updates since the commit?

**Comment by chenhengqi** [comment]
Nope. This should be good to go.

**Comment by chenhengqi** [comment]
May follow up new PR with some tests.

**Comment by defool** [comment]
@chenhengqi any progress?

**Comment by chenhengqi** [comment]
@defool This PR is ready to go, you can get it merged. This should close #290 .

**Comment by baiweiguo** [comment]
您好！您的邮件已收到，我将会尽快地进行处理，谢谢来信！

**Pull request merged**
