### PR TITLE
flag.Parse() must not be called during init. Instead, register flags during init, and call flag.Parse() in main().

### PR DESCRIPTION
**Pull request by BurningXFlame**
flag.Parse() must not be called during init. Instead, register flags during init, and call flag.Parse() in main().
Otherwise, if your own program or a 3rd-party lib(say, glog) you use registers flags during init and expects flags to be parsed during execution, your program will panic with "flag provided but not defined".

### CODE REVIEW

**Comment by BurningXFlame** [comment]
#112

**Comment by sandyskies** [comment]
please change to dev branch

**Comment by sandyskies** [comment]
This has conficts ，u have to check before being merged

**Comment by BurningXFlame** [comment]
What this PR proposed is the right way to use flag. 

#121 provides a fallback if flag.Parse() is not called in main(). It's good for backward compatibility.

BTW, for future use, have you considered modifying the auto-generated demo code, so that flag.Parse() is called explicitly in main()

**Pull request merged**
